<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
		

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="3.7.*" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\Restaurant.Reports\Restaurant.Reports.csproj" />
	  <ProjectReference Include="..\Restaurant.Core\Restaurant.Core.csproj" />
	  <ProjectReference Include="..\Restaurant.Infrastructure\Restaurant.Infrastructure.csproj" />
	</ItemGroup>

	<ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="https://www.schemastore.org/artifacthub-repo.json" /></VisualStudio></ProjectExtensions>

</Project>
