<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>UserLambda</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <Nullable>enable</Nullable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="1.10.0" />
    <ProjectReference Include="UserLambda.Api/UserLambda.Api.csproj" />
  </ItemGroup>

</Project>